//
// Created by karel on 15.04.2026.
//

#ifndef IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H
#define IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H

#define NODE_ID "6767"
#define DEVICE_MANUFACTURER "VUTID-6767"
#define DEVICE_FIRMWARE_VERSION "1.0.0"
#define DEVICE_CONNECTIVITY_TECHNOLOGY "WiFi"

#define GATE_END_OPEN_GPIO 23
#define GATE_END_CLOSE_GPIO 9
#define GATE_OBSTACLE_GPIO 12
#define GATE_LOCAL_BUTTON_GPIO 13
#define GATE_PWM_OPEN_GPIO 15
#define GATE_PWM_CLOSE_GPIO 22
#define WIFI_RESET_BUTTON_GPIO 20

#endif //IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H
