//
// Created by karel on 15.04.2026.
//

#ifndef IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H
#define IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H

#define NODE_ID "6767"
#define GATE_END_OPEN_GPIO 21
#define GATE_END_CLOSE_GPIO 22
#define GATE_OBSTACLE_GPIO 23


#endif //IOT_PROJEKT_VJEZDOVA_BRANA_CONFIG_H
